apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kznconstruction-com-tls
spec:
  secretName: kznconstruction-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: kznconstruction.com
  dnsNames:
    - kznconstruction.com
    - www.kznconstruction.com